
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyecto1c;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 17;
  public static final int RANGE = 7;
  public static final int RBRACE = 19;
  public static final int RPAREN = 15;
  public static final int LBRACE = 18;
  public static final int LPAREN = 14;
  public static final int INTERSEC = 4;
  public static final int COLON = 12;
  public static final int LETTER = 21;
  public static final int COMMA = 13;
  public static final int EOF = 0;
  public static final int NUMBER = 10;
  public static final int OPERATION = 11;
  public static final int SCOPE = 20;
  public static final int CONJ = 2;
  public static final int UNION = 3;
  public static final int EVALUATION = 8;
  public static final int error = 1;
  public static final int ARROW = 16;
  public static final int DIFF = 5;
  public static final int ASCII_CHAR = 22;
  public static final int COMPLEMENT = 6;
  public static final int VAR = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJ",
  "UNION",
  "INTERSEC",
  "DIFF",
  "COMPLEMENT",
  "RANGE",
  "EVALUATION",
  "VAR",
  "NUMBER",
  "OPERATION",
  "COLON",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "ARROW",
  "SEMICOLON",
  "LBRACE",
  "RBRACE",
  "SCOPE",
  "LETTER",
  "ASCII_CHAR"
  };
}

